# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HTMLmap
                                 A QGIS plugin
 HTMLmap
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-07
        git sha              : $Format:%H$
        copyright            : (C) 2020 by HTMLmap
        email                : HTMLmap
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import sys
import processing, os
from osgeo import ogr, osr, gdal
gdal.UseExceptions()

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from qgis.gui import QgsMapToolEmitPoint, QgsColorTextWidget, QgsColorButton
from qgis.utils import iface
from qgis.core import *
from qgis.utils import iface

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "\libs")
import folium
from folium import plugins
from folium.plugins import MeasureControl, FloatImage, MarkerCluster, TimestampedGeoJson, Search
from folium.features import CustomIcon, Template
import branca.colormap as cm
import json
import csv
import geopy
from geopy import geocoders
from geopy.geocoders import Nominatim, GoogleV3
import json

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .HTMLmap_dialog import HTMLmapDialog
import os.path


class HTMLmap:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'HTMLmap_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&HTMLmap')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('HTMLmap', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/HTMLmap/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'HTMLmap'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def atualizarCoordenadaPartidaOSM(self):
        self.dlg.lineEdit_5.clear()
        self.dlg.lineEdit_6.clear()
        enderecoPartida = self.dlg.lineEdit_3.text()
        locator = Nominatim(user_agent='myGeocoder')
        location1 = locator.geocode(enderecoPartida)
        CoordPartida = self.dlg.lineEdit_5.insert('{}'.format(location1.latitude))
        CoordPartida = self.dlg.lineEdit_6.insert('{}'.format(location1.longitude))

    def atualizarCoordenadaChegadaOSM(self):
        self.dlg.lineEdit_7.clear()
        self.dlg.lineEdit_8.clear()
        enderecoChegada = self.dlg.lineEdit_4.text()
        locator = Nominatim(user_agent='myGeocoder')
        location2 = locator.geocode(enderecoChegada)
        CoordPartida = self.dlg.lineEdit_7.insert('{}'.format(location2.latitude))
        CoordPartida = self.dlg.lineEdit_8.insert('{}'.format(location2.longitude))

    def atualizarCoordenadaPartidaGoogle(self):
        self.dlg.lineEdit_5.clear()
        self.dlg.lineEdit_6.clear()
        inputAddress = self.dlg.lineEdit_3.text()
        api_geocd_google = 'AIzaSyDIxergITTwdpMSMYdT7yAFyI6mrP3XDi0'
        api_key = self.dlg.lineEdit_13.text()
        g = geocoders.GoogleV3(api_key = api_key)
        location1 = g.geocode(inputAddress, timeout=10)
        CoordPartida = self.dlg.lineEdit_5.insert('{}'.format(location1.latitude))
        CoordPartida = self.dlg.lineEdit_6.insert('{}'.format(location1.longitude))

    def atualizarCoordenadaChegadaGoogle(self):
        self.dlg.lineEdit_7.clear()
        self.dlg.lineEdit_8.clear()
        inputAddress = self.dlg.lineEdit_4.text()
        api_geocd_google = 'AIzaSyDIxergITTwdpMSMYdT7yAFyI6mrP3XDi0'
        api_key = self.dlg.lineEdit_13.text()
        g = geocoders.GoogleV3(api_key = api_key)
        location2 = g.geocode(inputAddress, timeout=10)
        CoordPartida = self.dlg.lineEdit_7.insert('{}'.format(location2.latitude))
        CoordPartida = self.dlg.lineEdit_8.insert('{}'.format(location2.longitude))

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&HTMLmap'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = HTMLmapDialog()
            if self.dlg.radioButton.isChecked():
                self.dlg.pushButton_1.clicked.connect(self.atualizarCoordenadaPartidaOSM)
                self.dlg.pushButton_2.clicked.connect(self.atualizarCoordenadaChegadaOSM)
            if self.dlg.radioButton_2.isChecked():
                self.dlg.pushButton_1.clicked.connect(self.atualizarCoordenadaPartidaGoogle)
                self.dlg.pushButton_2.clicked.connect(self.atualizarCoordenadaChegadaGoogle)
            self.dlg.horizontalSlider.setValue(16)

            with open(r'C:\OSGeo4W64\apps\qgis\python\plugins\htmlmap\Base\fontawesone.txt', "r") as f:
                f.readline()
                for x in f:
                    comboText = self.dlg.comboBox_4.addItem(x)
                    comboText = self.dlg.comboBox_7.addItem(x)
                    comboText = self.dlg.comboBox_10.addItem(x)
            icon_color = {'beige', 'black', 'blue', 'cadetblue', 'darkblue', 'darkgreen', 'darkpurple', 'darkred', 'gray', 'green', 'lightblue', 'lightgray', 'lightgreen', 'lightred', 'orange', 'pink', 'purple', 'red', 'white'}
            add_icon_color = self.dlg.comboBox_3.addItems(icon_color)
            add_icon_color = self.dlg.comboBox_8.addItems(icon_color)


        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.

            latPartida = self.dlg.lineEdit_5.text()
            lat = float(latPartida)
            longPartida = self.dlg.lineEdit_6.text()
            long = float(longPartida)
            if self.dlg.mGroupBox_8.isChecked():
                latChegada = self.dlg.lineEdit_7.text()
                lat2 = float(latChegada)
                longChegada = self.dlg.lineEdit_8.text()
                long2 = float(longChegada)
                latcentral = (lat + lat2)/2
                longcentral = (long + long2)/2
                lat = latcentral
                long= longcentral

    #CRIAR O MAPA/TILE
            tiles = ('Open Street Map','Stamen Terrain', 'Stamen Toner', 'Stamen Watercolor', 'CartoDB Positron', 'CartoDB Dark_Matter')

    #IMAGEM DE SATÉLITE GOOGLE
            zoom = self.dlg.horizontalSlider.value()
            m = folium.Map(location=[lat, long], zoom_start=zoom, tiles=None, prefer_canvas =True)
            if self.dlg.comboBox.currentText() == 'Google Maps':
                folium.raster_layers.TileLayer(tiles='http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',attr='google',name='Google Maps',max_zoom=20,subdomains=['mt0', 'mt1', 'mt2', 'mt3'],overlay=False,control=True,).add_to(m)
            if self.dlg.comboBox.currentText() == 'Google Earth':
                folium.raster_layers.TileLayer(tiles='http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',attr='google',name='Google Earth',max_zoom=20,subdomains=['mt0', 'mt1', 'mt2', 'mt3'],overlay=False,control=True).add_to(m)
            if self.dlg.comboBox.currentText() == 'Open Street Map'or'Stamen Terrain'or 'Stamen Toner'or 'Stamen Watercolor'or 'CartoDB Positron'or 'CartoDB Dark_Matter':
                folium.raster_layers.TileLayer( tiles = self.dlg.comboBox.currentText(), attr='google', name= self.dlg.comboBox.currentText(), max_zoom=20, control_scale = True).add_to(m)

    #MINIMAP
            if self.dlg.checkBox.isChecked():
                minimap = plugins.MiniMap(position='bottomright', toggle_display=True,width=100, height=100, zoom_level_offset= -4, center_fixed=False, zoom_animation=True, minimized=False)
                m.add_child(minimap)

    #DESENHAR NA TELA
            if self.dlg.checkBox_2.isChecked():
                draw = plugins.Draw(position='bottomright',export =True)
                draw.add_to(m)

    #MEDIÇÃO EM TELA DE DISTANCIA E ÁREA
            if self.dlg.checkBox_3.isChecked():
                measure_control = plugins.MeasureControl(position='topright', active_color ='red', completed_color='red', primary_lenght_unit= 'meters')
                m.add_child(measure_control)

    # ADICIONAR ALGUMA IMAGEM NA TELA
            if self.dlg.checkBox_4.isChecked():
                url = self.dlg.mQgsFileWidget_5.filePath()
                FloatImage(url, bottom=92, left=1).add_to(m)

    #TELA CHEIA
            if self.dlg.checkBox_5.isChecked():
                plugins.Fullscreen(position='topleft').add_to(m)

    #LOCALIZAÇÃO DA PESSOA
            if self.dlg.checkBox_6.isChecked():
                plugins.LocateControl(position='topleft').add_to(m)
            if self.dlg.checkBox_8.isChecked():
            #    If you want get the user device positon after load the map, set auto_start=True
                plugins.LocateControl(auto_start=True).add_to(m)

    #LATITUDE E LONGITUDE PARA CLIQUES NO MAPA
            if self.dlg.checkBox_7.isChecked():
                m.add_child(folium.LatLngPopup())

            subgrupos = folium.FeatureGroup(name='Estilos de Mapas', control=False, show= False)
            m.add_child(subgrupos)
            if self.dlg.mGroupBox.isChecked():
                opcao1 = plugins.FeatureGroupSubGroup(subgrupos, self.dlg.lineEdit_11.text(), show= True)
                m.add_child(opcao1)
            if self.dlg.mGroupBox_2.isChecked():
                opcao2 = plugins.FeatureGroupSubGroup(subgrupos, self.dlg.lineEdit_12.text(), show= True)
                m.add_child(opcao2)
            if self.dlg.mGroupBox_3.isChecked():
                opcao3 = plugins.FeatureGroupSubGroup(subgrupos, self.dlg.lineEdit_10.text(), show= True)
                m.add_child(opcao3)
            if self.dlg.mGroupBox_8.isChecked():
                opcao4 = plugins.FeatureGroupSubGroup(subgrupos, 'Rota', show= True)
                m.add_child(opcao4)
#PONTO
            if self.dlg.mGroupBox.isChecked():
                PontosEntrada = self.dlg.mQgsFileWidget.filePath()
                PontosJSON = 'C:/OSGeo4W64/apps/qgis/python/plugins/htmlmap/Base/Pontos_json.geojson'
                gj = folium.GeoJson(PontosJSON)
                popupPontos = self.dlg.lineEdit.text()
                processing.run("native:reprojectlayer", {'INPUT':PontosEntrada,'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:4326'),'OPERATION':'+proj=pipeline +step +inv +proj=utm +zone=22 +south +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg','OUTPUT':PontosJSON})

                for feature in gj.data['features']:
                    if feature['geometry']['type'] == 'Point':
                        if self.dlg.comboBox_2.currentText() == 'Pin':
                            icon = self.dlg.comboBox_4.currentText()
                            color = self.dlg.mColorButton_11.color().name()
                            icon_color= self.dlg.mColorButton_5.color().name()
                            folium.Marker(location=list(reversed(feature['geometry']['coordinates'])),popup=popupPontos, icon=folium.Icon( icon=icon, color=color, icon_color=icon_color, prefix='fa')).add_to(opcao1)

                        if self.dlg.comboBox_2.currentText() == 'Beautify Icon':
                            icon = self.dlg.comboBox_4.currentText()
                            icon_color = self.dlg.mColorButton_5.color().name()
                            color = 'transparent'
                            tamanho = self.dlg.doubleSpinBox_4.value()
                            icon_size = (tamanho, tamanho)
                            icon_plane = plugins.BeautifyIcon(icon=icon, icon_size = icon_size, border_color='transparent', background_color = color, innerIconStyle= 'font-size:20px;padding-top:1px;', text_color=icon_color)
                            folium.Marker(location=list(reversed(feature['geometry']['coordinates'])),popup=popupPontos, icon=icon_plane).add_to(opcao1)

#LINHA
            if self.dlg.mGroupBox_2.isChecked():
                LinhaEntrada = self.dlg.mQgsFileWidget_2.filePath()
                LinhaJSON = 'C:/OSGeo4W64/apps/qgis/python/plugins/htmlmap/Base/Linha_json.geojson'
                espessura = self.dlg.doubleSpinBox_5.value()
                color = self.dlg.mColorButton.color().name()
                borda = self.dlg.mColorButton_13.color().name()
                popupLinhas = self.dlg.lineEdit_9.text()
                processing.run("native:reprojectlayer", {'INPUT':LinhaEntrada,'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:4326'),'OPERATION':'+proj=pipeline +step +inv +proj=utm +zone=22 +south +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg','OUTPUT':LinhaJSON})
                styleLinha = { "fillOpacity": 1, 'fillColor': borda, 'color': color, "weight": espessura, "opacity": 1.0}
                folium.GeoJson(LinhaJSON, style_function=lambda x: styleLinha, popup=popupLinhas).add_to(opcao2)
#POLÍGONO
            if self.dlg.mGroupBox_3.isChecked():
                PoligonoEntrada = self.dlg.mQgsFileWidget_3.filePath()
                popupPoligono = self.dlg.lineEdit_2.text()
                color = self.dlg.mColorButton_3.color().name()
                borda = self.dlg.mColorButton_2.color().name()
                transparencia = self.dlg.doubleSpinBox.value()
                PoligonoJSON = 'C:/OSGeo4W64/apps/qgis/python/plugins/htmlmap/Base/Poligono_json.geojson'
                processing.run("native:reprojectlayer", {'INPUT':PoligonoEntrada,'TARGET_CRS':QgsCoordinateReferenceSystem('EPSG:4326'),'OPERATION':'+proj=pipeline +step +inv +proj=utm +zone=22 +south +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg','OUTPUT':PoligonoJSON})
                stylePoligono = {'fillColor':color, "fillOpacity": transparencia,'color': borda, "weight": self.dlg.doubleSpinBox_2.value()}
                folium.GeoJson(PoligonoJSON, style_function=lambda x: stylePoligono).add_to(opcao3)


    #ADICIONAR IMAGEM - CERTO
    #        url = 'http://leafletjs.com/examples/custom-icons/{}'.format
    #        icon_image = url('leaf-red.png')
    #        icon3d = 'https://www.pngfind.com/pngs/m/218-2181815_download-setas-em-3d-png-images-background-setas.png'

    #        icon = CustomIcon(icon3d,icon_size=(19,47))
    #        marker = folium.Marker(location=[-25.4528, -49.2323],icon=icon,popup='Árvore')
    #        m.add_child(marker)

        #    icon_plane = plugins.BeautifyIcon(icon='tree', border_color='transparent', backgroundColor = 'transparent', iconSize= (22,22), border_width = 0.1, text_color='#83ca57',inner_icon_style='font-size:20px;padding-top:1px;')
        #    icon_number = plugins.BeautifyIcon(iconSize = (15, 15), border_width = 0, text_color='#000000', backgroundColor = 'transparent', number='A',inner_icon_style='font-size:15px')
        #    coord_arvores = [-25.4523, -49.2326]
        #    folium.Marker(location=coord_arvores,popup='Árvore', icon=icon_plane).add_to(m)
        #    folium.Marker(location=[-25.4527, -49.2331],popup='Bloco', icon=icon_number).add_to(m)
            #folium.LayerControl(collapsed=True).add_to(m)

            #icon3d = r'C:\Users\fabri\Desktop\Imagem1.svg'
            #icon = CustomIcon(icon3d,icon_size=(19,47))
            #marker = folium.Marker(location=[-25.4528, -49.2323],icon=icon,popup='Árvore')
            #m.add_child(marker)

#ORIGEM
            latPartida = self.dlg.lineEdit_5.text()
            latPartida = float(latPartida)
            longPartida = self.dlg.lineEdit_6.text()
            longPartida = float(longPartida)
            startPoint = '%s, %s [EPSG:4326]' % (longPartida, latPartida) #'-46.505448,-18.578563 [EPSG:4326]'
            if self.dlg.comboBox_9.currentText() == 'Pin':
                icon = self.dlg.comboBox_7.currentText()
                color = self.dlg.comboBox_3.currentText()
                icon_color= self.dlg.mColorButton_7.color().name()
                folium.Marker(location=[latPartida, longPartida],popup='Início', icon=folium.Icon( icon=icon, color=color, icon_color=icon_color, prefix='fa')).add_to(m)

            if self.dlg.comboBox_9.currentText() == 'Beautify Icon':
                icon = self.dlg.comboBox_7.currentText()
                #color = self.dlg.comboBox_7.currentText()
                color = 'transparent'
                icon_color = self.dlg.mColorButton_7.color().name()
                icon_size = (10, 10)
                icon_plane = plugins.BeautifyIcon(icon=icon,  prefix='fa', icon_size = icon_size, border_color='transparent', background_color = color, innerIconStyle= 'font-size:20px;padding-top:1px;', text_color=icon_color)
                folium.Marker(location=[latPartida, longPartida],popup='Início', icon=icon_plane).add_to(m)
#ROTA
            if self.dlg.mGroupBox_8.isChecked():
                latPartida = self.dlg.lineEdit_5.text()
                latPartida = float(latPartida)
                longPartida = self.dlg.lineEdit_6.text()
                longPartida = float(longPartida)
                latChegada = self.dlg.lineEdit_7.text()
                latChegada = float(latChegada)
                longChegada = self.dlg.lineEdit_8.text()
                longChegada = float(longChegada)

                lat, long = [round(latPartida, 3), round(latChegada, 3)], [round(longPartida, 3), round(longChegada, 3)]
                minlong, maxlong, minlat, maxlat = [min(long)+0.3, max(long)-0.3, min(lat)+0.3, max(lat)-0.3]
                extensao = '%s, %s, %s, %s [EPSG:4326]' % (minlong, maxlong, minlat, maxlat)
                redeOSM = 'C:/OSGeo4W64/apps/qgis/python/plugins/htmlmap/Base/Curitiba_vias01.shp'
                #malhaRota = 'C:/OSGeo4W64/apps/qgis/python/plugins/htmlmap/Base/cortado.gpkg'
                #processing.run("native:extractbyextent", {'INPUT':redeOSM,'EXTENT':extensao,'CLIP':False,'OUTPUT':malhaRota})

                startPoint = '%s, %s [EPSG:4326]' % (longPartida, latPartida) #'-46.505448,-18.578563 [EPSG:4326]'
                finalPoint = '%s, %s [EPSG:4326]' % (longChegada, latChegada) #'-46.507785,-18.577713 [EPSG:4326]'
                Ponto2 ='%s, %s' % (longChegada, latChegada)
                if self.dlg.comboBox_12.currentText() == 'Pin':
                    icon = self.dlg.comboBox_10.currentText()
                    color = self.dlg.comboBox_8.currentText()
                    icon_color= self.dlg.mColorButton_8.color().name()
                    folium.Marker(location=[ latChegada, longChegada],popup='Chegada', icon=folium.Icon( icon=icon, color=color, icon_color=icon_color, prefix='fa')).add_to(opcao4)

                if self.dlg.comboBox_12.currentText() == 'Beautify Icon':
                    icon = self.dlg.comboBox_10.currentText()
                    icon_color = self.dlg.mColorButton_8.color().name()
                    color = 'transparent'
                    icon_size = (10, 10)
                    icon_plane = plugins.BeautifyIcon(icon=icon, icon_size = icon_size, border_color='transparent', background_color = color, innerIconStyle= 'font-size:20px;padding-top:1px;', text_color=icon_color)
                    folium.Marker(location=[ latChegada, longChegada],popup='Chegada', icon=icon_plane).add_to(opcao4)

                rota = 'C:/OSGeo4W64/apps/qgis/python/plugins/htmlmap/Base/rota.geojson'
                processing.run("native:shortestpathpointtopoint", {'INPUT':redeOSM,'STRATEGY':0,'DIRECTION_FIELD':None,'VALUE_FORWARD':'','VALUE_BACKWARD':'','VALUE_BOTH':'','DEFAULT_DIRECTION':2,'SPEED_FIELD':None,'DEFAULT_SPEED':50,'TOLERANCE':0,'START_POINT': startPoint,'END_POINT': finalPoint,'OUTPUT':rota})

                with open(rota) as f:
                    data = json.load(f)
                for feature in data['features']:
                    coordenadasRota = (feature['geometry']['coordinates'])
                    coord_list = []
                for coord_pair in coordenadasRota:
                    json_coord_pair = {}
                    json_coord_pair = [(coord_pair[1]),(coord_pair[0])]
                    coord_list.append(json_coord_pair)

                    cor_rota= self.dlg.mColorButton_4.color().name()
                    cor_simbolo = self.dlg.mColorButton_6.color().name()

                    if self.dlg.mGroupBox_10.isChecked():
                        formato_simbolo = self.dlg.comboBox_5.currentText()
                        if self.dlg.comboBox_5.currentText() == 'Arredondado':
                            formato_simbolo = 'round'
                        if self.dlg.comboBox_5.currentText() == 'Quadrado':
                            formato_simbolo = 'butt'
                        if self.dlg.comboBox_5.currentText() == 'Retangular':
                            formato_simbolo = 'square'

                        juncao = self.dlg.comboBox_6.currentText()
                        if self.dlg.comboBox_6.currentText() == 'Arredondado':
                            juncao = 'round'
                        if self.dlg.comboBox_6.currentText() == 'Reto':
                            juncao = 'mitter'
                        if self.dlg.comboBox_6.currentText() == 'Cortado':
                            juncao = 'bevel'

                        plugins.AntPath([coord_list], popup= 'Rota', color=cor_rota,  weight=self.dlg.doubleSpinBox_8.value(), opacity = 1, delay = self.dlg.spinBox_3.value(), line_cap =formato_simbolo, line_join = juncao, dash_array = [10,20], pulse_color = cor_simbolo, reverse = True, hardwareAccelerated= True).add_to(opcao4)
                    else:
                        plugins.AntPath([coord_list], popup= 'Rota', color=cor_rota,  weight=self.dlg.doubleSpinBox_8.value(), opacity = 1, pulse_color = cor_rota, delay = 0).add_to(opcao4)
    #SALVAR MAPA
            folium.LayerControl(collapsed=True).add_to(m)
            salvarHTML = self.dlg.mQgsFileWidget_4.filePath() + ".html"
            m_save = m.save(salvarHTML)
            message = ("Finalizado: O arquivo foi processado e salvo.")
            self.iface.messageBar().pushMessage(message, level=0, duration=10)
